import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io

FloatingWindow {
    id: window
    title: "Monitor Settings"
    implicitWidth: 560
    implicitHeight: 500
    visible: true
    color: "transparent"

    // Live theme generated by your color script.
    // FileView watches the JSON, so changing colors.json updates this window immediately.
    FileView {
        id: colorsFile
        path: Quickshell.env("HOME") + "/.local/state/quickshell/user/generated/colors.json"
        watchChanges: true
        onFileChanged: reload()
    }

    function themeColor(name, fallback) {
        try {
            var data = JSON.parse(colorsFile.text())
            return data[name] || fallback
        } catch (e) {
            return fallback
        }
    }

    readonly property color backgroundColor: themeColor("background", "#0e1513")
    readonly property color surfaceColor: themeColor("surface", backgroundColor)
    readonly property color surfaceContainerLow: themeColor("surface_container_low", "#161d1c")
    readonly property color surfaceContainer: themeColor("surface_container", "#1a211f")
    readonly property color surfaceContainerHigh: themeColor("surface_container_high", "#252b2a")
    readonly property color surfaceContainerHighest: themeColor("surface_container_highest", "#303635")
    readonly property color surfaceContainerLowest: themeColor("surface_container_lowest", "#090f0e")
    readonly property color primaryColor: themeColor("primary", "#82d5c8")
    readonly property color onPrimaryColor: themeColor("on_primary", "#003731")
    readonly property color onSurfaceColor: themeColor("on_surface", "#dde4e1")
    readonly property color onSurfaceVariantColor: themeColor("on_surface_variant", "#bec9c6")
    readonly property color outlineColor: themeColor("outline", "#899390")
    readonly property color outlineVariantColor: themeColor("outline_variant", "#3f4947")
    readonly property color errorColor: themeColor("error", "#ffb4ab")

    property var monitors: []
    property string statusText: ""

    function refreshMonitors() {
        monitorProc.running = true
        refreshIcon.spin()
    }

    Process {
        id: monitorProc
        command: ["hyprctl", "monitors", "-j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    window.monitors = JSON.parse(text)
                } catch (e) {
                    console.warn("Failed parse hyprctl monitors -j:", e)
                    window.monitors = []
                }
            }
        }
    }

    Component.onCompleted: refreshMonitors()

    Rectangle {
        id: glass
        anchors.fill: parent
        radius: 22
        color: Qt.rgba(window.surfaceContainerHigh.r, window.surfaceContainerHigh.g, window.surfaceContainerHigh.b, 0.92)
        border.width: 1
        border.color: Qt.rgba(window.outlineColor.r, window.outlineColor.g, window.outlineColor.b, 0.38)

        opacity: 0
        scale: 0.94
        Component.onCompleted: entrance.start()
        transform: Scale { origin.x: glass.width / 2; origin.y: glass.height / 2 }

        ParallelAnimation {
            id: entrance
            NumberAnimation { target: glass; property: "opacity"; to: 1; duration: 260; easing.type: Easing.OutCubic }
            NumberAnimation { target: glass; property: "scale"; to: 1; duration: 260; easing.type: Easing.OutBack; easing.overshoot: 0.6 }
        }

        ColumnLayout {
            anchors.fill: parent
            anchors.margins: 18
            spacing: 12

            RowLayout {
                Layout.fillWidth: true
                spacing: 10

                MonitorLogo {
                    size: 26
                    accent: window.primaryColor
                    surfaceColor: window.surfaceContainerLowest
                    mutedColor: window.outlineColor
                }

                ColumnLayout {
                    spacing: 0
                    Layout.fillWidth: true
                    Label {
                        text: "Monitor Settings"
                        color: "#e8eeeb"
                        font.pixelSize: 17
                        font.weight: Font.DemiBold
                    }
                    Label {
                        text: window.monitors.length + " Display available"
                        color: "#a8b3b0"
                        font.pixelSize: 11
                    }
                }

                Rectangle {
                    id: refreshBtn
                    width: 30; height: 30
                    radius: 15
                    color: refreshArea.containsMouse ? Qt.rgba(window.onSurfaceColor.r, window.onSurfaceColor.g, window.onSurfaceColor.b, 0.10) : Qt.rgba(window.onSurfaceColor.r, window.onSurfaceColor.g, window.onSurfaceColor.b, 0.04)
                    border.color: Qt.rgba(window.outlineColor.r, window.outlineColor.g, window.outlineColor.b, 0.22)
                    border.width: 1

                    Behavior on color { ColorAnimation { duration: 120 } }

                    Text {
                        id: refreshIcon
                        anchors.centerIn: parent
                        text: "𓃵"
                        color: "#e8eeeb"
                        font.pixelSize: 16

                        function spin() { spinAnim.start() }
                        RotationAnimation {
                            id: spinAnim
                            target: refreshIcon
                            from: 0; to: 360
                            duration: 500
                            easing.type: Easing.InOutCubic
                        }
                    }

                    MouseArea {
                        id: refreshArea
                        anchors.fill: parent
                        hoverEnabled: true
                        cursorShape: Qt.PointingHandCursor
                        onClicked: window.refreshMonitors()
                    }
                }
            }

            Rectangle {
                Layout.fillWidth: true
                height: 1
                color: Qt.rgba(window.outlineVariantColor.r, window.outlineVariantColor.g, window.outlineVariantColor.b, 0.55)
            }

            Label {
                visible: window.monitors.length === 0
                text: "No monitor detected, or hyprctl failed to run."
                color: window.errorColor
            }

            ListView {
                id: list
                Layout.fillWidth: true
                Layout.fillHeight: true
                spacing: 10
                clip: true
                model: window.monitors
                delegate: MonitorRow {
                    width: list.width
                    monitorData: modelData
                    accent: window.primaryColor
                    textColor: window.onSurfaceColor
                    mutedColor: window.onSurfaceVariantColor
                    surfaceColor: window.surfaceContainerLow
                    surfaceVariantColor: window.surfaceContainerHigh
                    outlineColor: window.outlineColor
                    outlineVariantColor: window.outlineVariantColor
                    onPrimaryColor: window.onPrimaryColor
                    onStatus: (msg) => window.statusText = msg
                }

                add: Transition {
                    NumberAnimation { properties: "opacity"; from: 0; to: 1; duration: 220 }
                    NumberAnimation { properties: "y"; from: 12; duration: 220; easing.type: Easing.OutCubic }
                }
            }

            Label {
                text: window.statusText
                color: window.primaryColor
                visible: text.length > 0
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                font.pixelSize: 12
            }
        }
    }
}
